# Generated by Django 4.0 on 2024-06-20 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='owner',
            new_name='responsible',
        ),
    ]
