# Generated by Django 4.0 on 2024-06-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_contact_mobile_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='avatar',
            field=models.ImageField(default='profile_pics/user.svg', upload_to='profile_pics/'),
        ),
    ]
