# Generated by Django 5.1 on 2025-06-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_skill_user_address_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emergency_contact',
            field=models.TextField(blank=True, help_text='Имя, телефон, кем приходится', null=True, verbose_name='Экстренный контакт'),
        ),
    ]
