# python version 1.0						DO NOT EDIT
#
# Generated by smidump version 0.4.8:
#
#   smidump -f python DKSF-73-1-X-X-1

FILENAME = "mibs/72.1.RMB.mib"

MIB = {
    "moduleName" : "DKSF-73-1-X-X-1",

    "DKSF-73-1-X-X-1" : {
        "nodetype" : "module",
        "language" : "SMIv1",
        "organization" :    
            """Alentis Electronics""",
        "contact" : 
            """developers@netping.ru""",
        "description" :
            """Generic MIB for NetPing remote sensing and control""",
        "revisions" : (
            {
                "date" : "2021-02-19 00:00",
                "description" :
                    """Initial release, based on DKSF70 UniPing Server Solution""",
            },
        ),
        "identity node" : "netPingServerSolutionV5noGsm",
    },

    "imports" : (
        {"module" : "", "name" : "enterprises"},
        {"module" : "", "name" : "MODULE-IDENTITY"},
        {"module" : "", "name" : "OBJECT-TYPE"},
        {"module" : "", "name" : "Counter32"},
        {"module" : "", "name" : "Integer32"},
        {"module" : "", "name" : "Unsigned32"},
        {"module" : "", "name" : "NOTIFICATION-TYPE"},
        {"module" : "", "name" : "TEXTUAL-CONVENTION"},
        {"module" : "", "name" : "DisplayString"},
        {"module" : "", "name" : "snmpTraps"},
    ),

    "typedefs" : {
        "FixedPoint1000" : {
            "basetype" : "Integer32",
            "status" : "current",
            "format" : "d-3",
            "description" :
                """Fixed-point value as Integer, 3 decimal gigits after point (i.e. value*1000 rounded to Integer)""",
        },
    }, # typedefs

}
