# Generated by Django 5.1 on 2025-05-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100, verbose_name='Имя оцениваемого (текст)')),
                ('responses', models.JSONField(verbose_name='Ответы (ID вопроса -> ответ)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время оценки')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст вопроса')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('answer_options', models.JSONField(blank=True, help_text='Список строк с вариантами ответа, например ["Да", "Нет", "Затрудняюсь ответить"] или ["1", "2", "3", "4", "5"]. Оставьте пустым для свободного ответа.', null=True, verbose_name='Варианты ответа (JSON list)')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['questionnaire', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название опросника')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Активные опросники доступны для выбора при оценке.', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Опросник',
                'verbose_name_plural': 'Опросники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Telegram ID')),
                ('approved', models.BooleanField(default=False, verbose_name='Подтвержден')),
                ('notified_on_approval', models.BooleanField(default=False, verbose_name='Уведомлен о подтверждении')),
            ],
            options={
                'verbose_name': 'Telegram Пользователь',
                'verbose_name_plural': 'Telegram Пользователи',
            },
        ),
    ]
