# Generated by Django 5.1 on 2025-05-03 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrbot', '0001_initial'),
        ('user_profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_in', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник (объект User)'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_in_role', to='user_profiles.role', verbose_name='Роль (контекст)'),
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hrbot.questionnaire', verbose_name='Опросник'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='hrbot.questionnaire', verbose_name='Использованный опросник'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь Django'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to='hrbot.telegramuser', verbose_name='Оценщик (TG User)'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['questionnaire', 'order'], name='hrbot_quest_questio_e61534_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['-timestamp'], name='hrbot_evalu_timesta_50df15_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['evaluator'], name='hrbot_evalu_evaluat_978fb8_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['employee'], name='hrbot_evalu_employe_f49d75_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['questionnaire'], name='hrbot_evalu_questio_511de4_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['role'], name='hrbot_evalu_role_id_0c3bdc_idx'),
        ),
    ]
