# Generated by Django 5.1 on 2025-04-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Telegram Пользователь', 'verbose_name_plural': 'Telegram Пользователи'},
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='notified_on_approval',
            field=models.BooleanField(default=False, verbose_name='Уведомлен о подтверждении'),
        ),
    ]
