# Generated by Django 5.1 on 2025-04-20 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrbot', '0002_alter_telegramuser_options_and_more'),
        ('user_profiles', '0007_user_roles_alter_taskuserrole_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название опросника')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Активные опросники доступны для выбора при оценке.', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Опросник',
                'verbose_name_plural': 'Опросники',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['questionnaire', 'order'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='role',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_in', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник (объект User)'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='employee_name',
            field=models.CharField(max_length=100, verbose_name='Имя оцениваемого (текст)'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to='hrbot.telegramuser', verbose_name='Оценщик (TG User)'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='responses',
            field=models.JSONField(verbose_name='Ответы (ID вопроса -> ответ)'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_in_role', to='user_profiles.role', verbose_name='Роль (контекст)'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время оценки'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь Django'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='questionnaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='hrbot.questionnaire', verbose_name='Использованный опросник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hrbot.questionnaire', verbose_name='Опросник'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['-timestamp'], name='hrbot_evalu_timesta_50df15_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['evaluator'], name='hrbot_evalu_evaluat_978fb8_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['employee'], name='hrbot_evalu_employe_f49d75_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['questionnaire'], name='hrbot_evalu_questio_511de4_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['role'], name='hrbot_evalu_role_id_0c3bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['questionnaire', 'order'], name='hrbot_quest_questio_e61534_idx'),
        ),
    ]
