# Generated by Django 5.1 on 2025-04-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrbot', '0003_questionnaire_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_options',
            field=models.JSONField(blank=True, help_text='Список строк с вариантами ответа, например ["Да", "Нет", "Затрудняюсь ответить"] или ["1", "2", "3", "4", "5"]. Оставьте пустым для свободного ответа.', null=True, verbose_name='Варианты ответа (JSON list)'),
        ),
    ]
