# Generated by Django 5.1 on 2025-06-15 23:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReadStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_read_timestamp', models.DateTimeField(auto_now=True, verbose_name='Время последнего прочтения')),
            ],
            options={
                'verbose_name': 'Статус прочтения',
                'verbose_name_plural': 'Статусы прочтения',
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emoji', models.CharField(max_length=50, verbose_name='Эмодзи')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Реакция',
                'verbose_name_plural': 'Реакции',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название комнаты')),
                ('slug', models.SlugField(help_text='Автоматически генерируется из названия, если не указано. Используется в URL.', max_length=110, unique=True, verbose_name='Slug (URL)')),
                ('private', models.BooleanField(db_index=True, default=False, verbose_name='Приватная?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Последняя активность')),
                ('is_archived', models.BooleanField(db_index=True, default=False, verbose_name='В архиве?')),
            ],
            options={
                'verbose_name': 'Чат-комната',
                'verbose_name_plural': 'Чат-комнаты',
                'ordering': ('-last_activity_at',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='chat_files/%Y/%m/%d/', verbose_name='Файл')),
                ('date_added', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Добавлено')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Отредактировано')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Удалено?')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='room.message', verbose_name='В ответ на')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чата',
                'ordering': ('date_added',),
            },
        ),
    ]
