# Generated by Django 5.1 on 2025-05-14 14:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('-last_activity_at',), 'verbose_name': 'Чат-комната', 'verbose_name_plural': 'Чат-комнаты'},
        ),
        migrations.RemoveIndex(
            model_name='messagereadstatus',
            name='room_messag_user_id_5b36e0_idx',
        ),
        migrations.RemoveIndex(
            model_name='room',
            name='room_room_is_arch_ab74c7_idx',
        ),
        migrations.AddField(
            model_name='room',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='room',
            name='last_activity_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Последняя активность'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_added',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название комнаты'),
        ),
        migrations.AlterField(
            model_name='room',
            name='private',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Приватная?'),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(max_length=110, unique=True, verbose_name='Slug (URL)'),
        ),
        migrations.AddIndex(
            model_name='messagereadstatus',
            index=models.Index(fields=['user', 'room', 'last_read_message'], name='room_messag_user_id_fed4a4_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['message', 'user', 'emoji'], name='room_reacti_message_a746ee_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_archived', 'private', '-last_activity_at'], name='room_room_is_arch_8f5b5b_idx'),
        ),
    ]
