# Generated by Django 5.1 on 2025-05-17 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reaction',
            name='room_reacti_message_d469bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='reaction',
            name='room_reacti_message_a746ee_idx',
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='chat_files/%Y/%m/%d/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='room',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(help_text='Автоматически генерируется из названия, если не указано. Используется в URL.', max_length=110, unique=True, verbose_name='Slug (URL)'),
        ),
        migrations.AddIndex(
            model_name='messagereadstatus',
            index=models.Index(fields=['user', 'room', 'last_read_timestamp'], name='room_messag_user_id_b45bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['message', 'emoji', 'created_at'], name='room_reacti_message_5e294d_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['name'], name='room_room_name_1136a3_idx'),
        ),
    ]
