# Generated by Django 5.1 on 2025-04-30 03:45

import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_messagereadstatus_reaction_alter_room_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('date_added',), 'verbose_name': 'Сообщение чата', 'verbose_name_plural': 'Сообщения чата'},
        ),
        migrations.AlterModelOptions(
            name='messagereadstatus',
            options={'verbose_name': 'Статус прочтения', 'verbose_name_plural': 'Статусы прочтения'},
        ),
        migrations.AlterModelOptions(
            name='reaction',
            options={'ordering': ('created_at',), 'verbose_name': 'Реакция на сообщение', 'verbose_name_plural': 'Реакции на сообщения'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('-updated_at',), 'verbose_name': 'Чат-комната', 'verbose_name_plural': 'Чат-комнаты'},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='room_messag_search__6f080a_gin',
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отредактировано'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/%Y/%m/%d/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалено?'),
        ),
        migrations.AlterField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='room.message', verbose_name='В ответ на'),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='room.room', verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='message',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='messagereadstatus',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.message', verbose_name='Последнее прочитанное сообщение'),
        ),
        migrations.AlterField(
            model_name='messagereadstatus',
            name='last_read_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последнего прочтения'),
        ),
        migrations.AlterField(
            model_name='messagereadstatus',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room', verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='messagereadstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='emoji',
            field=models.CharField(max_length=50, verbose_name='Эмодзи'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='room.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве?'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название комнаты'),
        ),
        migrations.AlterField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='room',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Приватная?'),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug (URL)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AddIndex(
            model_name='messagereadstatus',
            index=models.Index(fields=['user', 'room'], name='room_messag_user_id_5b36e0_idx'),
        ),
    ]
