# Generated by Django 5.1 on 2025-04-30 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_alter_message_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reaction',
            options={'ordering': ('created_at',), 'verbose_name': 'Реакция', 'verbose_name_plural': 'Реакции'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='search_vector',
        ),
        migrations.AlterField(
            model_name='messagereadstatus',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.message', verbose_name='Последнее прочитанное'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='В архиве?'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'is_deleted', 'date_added'], name='room_messag_room_id_53584e_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['message', 'emoji'], name='room_reacti_message_d469bc_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_archived', 'private'], name='room_room_is_arch_ab74c7_idx'),
        ),
    ]
