# Generated by Django 5.0.6 on 2024-07-01 18:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_alter_sensordata_uptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='heat_index',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='humidity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temperature',
            field=models.FloatField(null=True),
        ),
    ]
