# Generated by Django 5.0.6 on 2024-07-01 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_sensordata_status_alter_sensordata_datetime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordata',
            options={'permissions': [('can_view_sensor_data', 'Can view sensor data'), ('can_edit_sensor_data', 'Can edit sensor data')]},
        ),
    ]
