# Generated by Django 5.0.6 on 2024-07-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0009_historicalsensordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsensordata',
            name='uptime',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='uptime',
            field=models.FloatField(),
        ),
    ]
