# Generated by Django 4.0 on 2024-06-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counterparty', '0002_counterparty_addr_city_counterparty_addr_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterparty',
            name='responsible',
        ),
    ]
