# Generated by Django 5.1 on 2025-03-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('task_number', models.CharField(blank=True, db_index=True, max_length=20, unique=True, verbose_name='Номер задачи')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('on_hold', 'Отложена'), ('completed', 'Выполнена'), ('cancelled', 'Отменена'), ('overdue', 'Просрочена')], db_index=True, default='new', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Высокий'), (2, 'Выше среднего'), (3, 'Средний'), (4, 'Ниже среднего'), (5, 'Низкий')], db_index=True, default=3)),
                ('deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_time', models.DurationField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['priority', 'deadline', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория задач',
                'verbose_name_plural': 'Категории задач',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('photo', models.ImageField(upload_to='task_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание фотографии')),
            ],
            options={
                'verbose_name': 'Фотография к задаче',
                'verbose_name_plural': 'Фотографии к задачам',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название подкатегории')),
                ('description', models.TextField(blank=True, verbose_name='Описание подкатегории')),
            ],
            options={
                'verbose_name': 'Подкатегория задач',
                'verbose_name_plural': 'Подкатегории задач',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название кампании')),
                ('description', models.TextField(blank=True, verbose_name='Описание кампании')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
            ],
            options={
                'verbose_name': 'Кампания',
                'verbose_name_plural': 'Кампании',
                'ordering': ['name', '-created_at'],
                'indexes': [models.Index(fields=['name'], name='campaign_name_idx')],
            },
        ),
    ]
