# Generated by Django 5.1 on 2025-06-17 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
        ("user_profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskcategory",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_categories",
                to="user_profiles.department",
                verbose_name="Отдел",
            ),
        ),
    ]
