# Generated by Django 5.1 on 2025-06-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriorityDeadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (5, "Низкий"),
                            (4, "Ниже среднего"),
                            (3, "Средний"),
                            (2, "Выше среднего"),
                            (1, "Высокий"),
                        ],
                        unique=True,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "days",
                    models.PositiveIntegerField(default=7, verbose_name="Срок (дней)"),
                ),
            ],
            options={
                "verbose_name": "Срок по приоритету",
                "verbose_name_plural": "Сроки по приоритетам",
                "ordering": ["priority"],
            },
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('tasks', 'PriorityDeadline').objects.bulk_create([
                apps.get_model('tasks', 'PriorityDeadline')(priority=1, days=1),
                apps.get_model('tasks', 'PriorityDeadline')(priority=2, days=3),
                apps.get_model('tasks', 'PriorityDeadline')(priority=3, days=7),
                apps.get_model('tasks', 'PriorityDeadline')(priority=4, days=14),
                apps.get_model('tasks', 'PriorityDeadline')(priority=5, days=30),
            ], ignore_conflicts=True),
            migrations.RunPython.noop,
        ),
    ]
