# Generated by Django 5.1 on 2025-03-18 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('user_profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.campaign'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='user_profiles.team'),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='last_assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_category_tasks', to='user_profiles.team'),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.taskcategory'),
        ),
        migrations.AddField(
            model_name='taskphoto',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_photos', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tasks.taskphoto'),
        ),
        migrations.AddField(
            model_name='tasksubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='tasks.taskcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='task',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.tasksubcategory'),
        ),
        migrations.AddIndex(
            model_name='taskcategory',
            index=models.Index(fields=['name'], name='taskcategory_name_idx'),
        ),
        migrations.AddIndex(
            model_name='taskphoto',
            index=models.Index(fields=['task'], name='taskphoto_task_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksubcategory',
            index=models.Index(fields=['category', 'name'], name='subcat_catname_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksubcategory',
            index=models.Index(fields=['name'], name='tasksubcategory_name_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_number'], name='task_task_number_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='task_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='task_priority_idx'),
        ),
    ]
