# Generated by Django 5.1 on 2025-03-22 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
        ('user_profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubcategory',
            name='last_assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_subcategory_tasks', to='user_profiles.team'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('task_number',), name='unique_task_number'),
        ),
        migrations.AddConstraint(
            model_name='tasksubcategory',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_subcategory_name'),
        ),
    ]
