# Generated by Django 5.1 on 2025-03-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasksubcategory_last_assigned_team_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campaign',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='campaign',
            new_name='project',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='project_name_idx',
            old_name='campaign_name_idx',
        ),
    ]
