# Generated by Django 5.1 on 2025-05-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_options_remove_task_task_deadline_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('backlog', 'Бэклог'), ('new', 'Новая'), ('in_progress', 'В работе'), ('on_hold', 'Отложена'), ('completed', 'Выполнена'), ('cancelled', 'Отменена'), ('overdue', 'Просрочена')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
