# Generated by Django 5.1 on 2025-03-31 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_campaign_project_rename_campaign_task_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name', '-created_at'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='taskphoto',
            options={'ordering': ['-created_at'], 'verbose_name': 'Фотография к задаче', 'verbose_name_plural': 'Фотографии к задачам'},
        ),
        migrations.AlterModelOptions(
            name='tasksubcategory',
            options={'ordering': ['category__name', 'name'], 'verbose_name': 'Подкатегория задач', 'verbose_name_plural': 'Подкатегории задач'},
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_task_number',
        ),
        migrations.RemoveConstraint(
            model_name='tasksubcategory',
            name='unique_subcategory_name',
        ),
        migrations.RemoveIndex(
            model_name='tasksubcategory',
            name='subcat_catname_idx',
        ),
        migrations.RenameIndex(
            model_name='tasksubcategory',
            new_name='subcat_name_idx',
            old_name='tasksubcategory_name_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='task',
            name='team',
        ),
        migrations.RemoveField(
            model_name='taskcategory',
            name='last_assigned_team',
        ),
        migrations.RemoveField(
            model_name='taskphoto',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='tasksubcategory',
            name='last_assigned_team',
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='title placeholder', max_length=255, verbose_name='Название задачи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskphoto',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.taskcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Срок выполнения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Оценка времени'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(5, 'Низкий'), (4, 'Ниже среднего'), (3, 'Средний'), (2, 'Выше среднего'), (1, 'Высокий')], db_index=True, default=3, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('on_hold', 'Отложена'), ('completed', 'Выполнена'), ('cancelled', 'Отменена'), ('overdue', 'Просрочена')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.tasksubcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_number',
            field=models.CharField(blank=True, db_index=True, max_length=25, unique=True, verbose_name='Номер задачи'),
        ),
        migrations.AlterField(
            model_name='taskphoto',
            name='photo',
            field=models.ImageField(upload_to='task_photos/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='taskphoto',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tasks.task', verbose_name='Задача'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deadline'], name='task_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project'], name='task_project_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by'], name='task_creator_idx'),
        ),
        migrations.AddConstraint(
            model_name='tasksubcategory',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_subcategory_per_category'),
        ),
    ]
