# Generated by Django 5.1 on 2025-05-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_number',
            field=models.CharField(blank=True, db_index=True, max_length=40, unique=True, verbose_name='Номер задачи'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='role',
            field=models.CharField(choices=[('responsible', 'Ответственный'), ('executor', 'Исполнитель'), ('watcher', 'Наблюдатель'), ('reporter', 'Автор/Заявитель')], max_length=20, verbose_name='Роль'),
        ),
    ]
