# Generated by Django 5.1 on 2025-05-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_task_number_alter_taskassignment_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, help_text='Планируемая дата завершения задачи.', null=True, verbose_name='срок выполнения'),
        ),
    ]
