# Generated by Django 5.1 on 2025-05-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('on_hold', 'Отложена'), ('completed', 'Выполнена'), ('cancelled', 'Отменена'), ('overdue', 'Просрочена')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
