# Generated by Django 5.1 on 2025-04-28 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='project_name_idx',
        ),
    ]
