# Generated by Django 5.1 on 2025-04-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
    ]
