# Generated by Django 5.1 on 2025-04-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='task_photos/', verbose_name='Фотография'),
        ),
    ]
