# Generated by Django 5.1 on 2025-03-30 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import now

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_campaign_project_rename_campaign_task_project_and_more'),
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskuserrole',
            options={'ordering': ['task', 'user'], 'verbose_name': 'Роль пользователя в задаче', 'verbose_name_plural': 'Роли пользователей в задачах'},
        ),
        migrations.RemoveIndex(
            model_name='taskuserrole',
            name='taskuserrole_unique_role_idx',
        ),
        migrations.AlterUniqueTogether(
            name='taskuserrole',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='taskuserrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=now, verbose_name='Дата назначения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskuserrole',
            name='role',
            field=models.CharField(choices=[('executor', 'Исполнитель'), ('watcher', 'Наблюдатель'), ('responsible', 'Ответственный')], db_index=True, max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='taskuserrole',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='tasks.task', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='taskuserrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_roles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='taskuserrole',
            unique_together={('task', 'user')},
        ),
        migrations.AddIndex(
            model_name='taskuserrole',
            index=models.Index(fields=['task', 'user'], name='taskuserrole_task_user_idx'),
        ),
        migrations.AddIndex(
            model_name='taskuserrole',
            index=models.Index(fields=['task'], name='taskuserrole_task_idx'),
        ),
        migrations.AddIndex(
            model_name='taskuserrole',
            index=models.Index(fields=['user'], name='taskuserrole_user_idx'),
        ),
    ]
