# Generated by Django 5.1 on 2025-06-22 17:36
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название навыка"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Адрес проживания"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_contact",
            field=models.TextField(
                blank=True, null=True, verbose_name="Экстренный контакт"

            ),
        ),
        migrations.AddField(
            model_name="user",
            name="employee_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Табельный номер",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_time", "Полная занятость"),
                    ("part_time", "Частичная занятость"),
                    ("contractor", "Подрядчик"),
                    ("intern", "Стажер"),
                ],
                default="full_time",
                max_length=20,
                null=True,
                verbose_name="Тип занятости",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="hire_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата приема на работу"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports_to",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Прямой руководитель",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="personal_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Личный Email"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="termination_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата увольнения"
            ),
        ),
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("contract", "Трудовой договор"),
                            ("passport", "Паспортные данные"),
                            ("nda", "Соглашение о неразглашении"),
                            ("other", "Прочее"),
                        ],
                        max_length=20,
                        verbose_name="Тип документа",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="employee_documents/%Y/%m/",
                        verbose_name="Файл документа",
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата выдачи"),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания срока"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ сотрудника",
                "verbose_name_plural": "Документы сотрудников",
            },
        ),
        migrations.CreateModel(
            name="EmployeeSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "Новичок"),
                            (2, "Средний уровень"),
                            (3, "Продвинутый"),
                            (4, "Эксперт"),
                        ],
                        default=1,
                        verbose_name="Уровень владения",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="user_profiles.skill",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "skill")},
            },
        ),
    ]
