# Generated by Django 5.1 on 2025-05-30 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammembershipuser',
            options={'ordering': ['team__name', 'user__username'], 'verbose_name': 'Членство в команде (User-Team)', 'verbose_name_plural': 'Членства в командах (User-Team)'},
        ),
    ]
