# Generated by Django 5.1 on 2025-05-03 17:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Роль/Должность', 'verbose_name_plural': 'Роли/Должности'},
        ),
        migrations.AlterModelOptions(
            name='taskuserrole',
            options={'ordering': ['task', 'user'], 'verbose_name': 'Роль пользователя в задаче', 'verbose_name_plural': 'Роли пользователей в задачах'},
        ),
        migrations.RenameIndex(
            model_name='taskuserrole',
            new_name='user_profil_task_id_f4195b_idx',
            old_name='taskuserrole_task_user_idx',
        ),
        migrations.RenameIndex(
            model_name='taskuserrole',
            new_name='user_profil_task_id_e0a6a7_idx',
            old_name='taskuserrole_task_role_idx',
        ),
        migrations.RenameIndex(
            model_name='taskuserrole',
            new_name='user_profil_user_id_67b2b1_idx',
            old_name='taskuserrole_user_role_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание роли'),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_primary', to='user_profiles.role', verbose_name='Основная Роль/Должность'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название отдела'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название роли/должности'),
        ),
        migrations.AlterField(
            model_name='taskuserrole',
            name='role',
            field=models.CharField(choices=[('responsible', 'Ответственный'), ('executor', 'Исполнитель'), ('watcher', 'Наблюдатель')], db_index=True, max_length=20, verbose_name='Роль в задаче'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность (текст)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Номер телефона'),
        ),
    ]
