# Generated by Django 5.1 on 2025-03-31 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_project_options_alter_taskphoto_options_and_more'),
        ('user_profiles', '0002_alter_taskuserrole_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=150, verbose_name='Название отдела')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='team',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='taskuserrole',
            options={'ordering': ['task__id', 'user__username'], 'verbose_name': 'Роль пользователя в задаче', 'verbose_name_plural': 'Роли пользователей в задачах'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name', 'username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveIndex(
            model_name='taskuserrole',
            name='taskuserrole_task_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskuserrole',
            name='taskuserrole_user_idx',
        ),
        migrations.AddField(
            model_name='taskuserrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='taskuserrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='taskuserrole',
            name='role',
            field=models.CharField(choices=[('responsible', 'Ответственный'), ('executor', 'Исполнитель'), ('watcher', 'Наблюдатель')], db_index=True, max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название команды'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL, verbose_name='Лидер команды'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/default_avatar.svg', upload_to='profile_pics/', verbose_name='Аватар'),
        ),
        migrations.AddIndex(
            model_name='taskuserrole',
            index=models.Index(fields=['task', 'role'], name='taskuserrole_task_role_idx'),
        ),
        migrations.AddIndex(
            model_name='taskuserrole',
            index=models.Index(fields=['user', 'role'], name='taskuserrole_user_role_idx'),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель отдела'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='user_profiles.department', verbose_name='Вышестоящий отдел'),
        ),
        migrations.AddField(
            model_name='team',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='user_profiles.department', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='user_profiles.department', verbose_name='Отдел'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name'], name='user_profil_name_35a5ea_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['department'], name='user_profil_departm_092edf_idx'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='user_profil_name_aa3592_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent'], name='user_profil_parent__081137_idx'),
        ),
    ]
