# Generated by Django 5.1 on 2025-05-03 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_alter_role_options_alter_taskuserrole_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название должности')),
                ('description', models.TextField(blank=True, verbose_name='Описание должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='primary_role',
        ),
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='user_profiles.jobtitle', verbose_name='Должность'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
