# Generated by Django 5.1 on 2025-03-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_department_delete_role_remove_userprofile_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/user.svg', upload_to='profile_pics/', verbose_name='Аватар'),
        ),
    ]
