# Generated by Django 5.1 on 2025-04-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0006_role_alter_taskuserrole_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='user_profiles.role', verbose_name='Роли'),
        ),
        migrations.AlterField(
            model_name='taskuserrole',
            name='role',
            field=models.CharField(choices=[('responsible', 'Ответственный'), ('executor', 'Исполнитель'), ('watcher', 'Наблюдатель')], db_index=True, max_length=20, verbose_name='Роль'),
        ),
    ]
