# Generated by Django 4.0 on 2024-06-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0008_alter_user_image_alter_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
