# Generated by Django 5.1 on 2025-05-03 14:54

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата/Время начала')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('is_complete', models.BooleanField(db_index=True, default=False, verbose_name='Завершен')),
                ('completion_time', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В процессе'), ('submitted', 'Отправлено'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='in_progress', max_length=20, verbose_name='Статус')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Время одобрения')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Внешняя ссылка')),
            ],
            options={
                'verbose_name': 'Выполненный чеклист',
                'verbose_name_plural': 'Выполненные чеклисты',
                'ordering': ['-performed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название Точки/Комнаты')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Точка/Комната Чеклиста',
                'verbose_name_plural': 'Точки/Комнаты Чеклистов',
                'ordering': ['location__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True, verbose_name='Ответ (текст/выбор)')),
                ('numeric_value', models.FloatField(blank=True, null=True, verbose_name='Числовое значение')),
                ('boolean_value', models.BooleanField(blank=True, null=True, verbose_name='Булево значение')),
                ('date_value', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('datetime_value', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время')),
                ('time_value', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='checklist_files/', verbose_name='Файл')),
                ('media_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на медиа')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('ok', 'OK'), ('not_ok', 'Не OK'), ('na', 'Неприменимо')], db_index=True, default='pending', max_length=20, verbose_name='Статус пункта')),
                ('is_corrected', models.BooleanField(default=False, verbose_name='Исправлено')),
                ('recorded_at', models.DateTimeField(auto_now=True, verbose_name='Записано')),
            ],
            options={
                'verbose_name': 'Результат пункта',
                'verbose_name_plural': 'Результаты пунктов',
                'ordering': ['checklist_run', 'template_item__section__order', 'template_item__order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название секции')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Секция шаблона',
                'verbose_name_plural': 'Секции шаблона',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('version', models.CharField(blank=True, default='1.0', max_length=20, verbose_name='Версия')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивирован')),
                ('frequency', models.CharField(blank=True, max_length=50, verbose_name='Периодичность')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='След. дата выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Шаблон чеклиста',
                'verbose_name_plural': 'Шаблоны чеклистов',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.TextField(verbose_name='Текст пункта/вопроса')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('answer_type', models.CharField(choices=[('text', 'Текстовое поле'), ('number', 'Числовое поле'), ('scale_1_4', 'Оценка 1–4'), ('scale_1_5', 'Оценка 1–5'), ('yes_no', 'Да / Нет'), ('yes_no_meh', 'Да / Нет / Не очень'), ('boolean', 'Да/Нет (Boolean)'), ('date', 'Дата'), ('datetime', 'Дата и время'), ('time', 'Время'), ('file', 'Файл'), ('url', 'Ссылка')], default='text', max_length=20, verbose_name='Тип ответа')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='Подсказка')),
                ('default_value', models.CharField(blank=True, max_length=255, verbose_name='Значение по умолчанию')),
            ],
            options={
                'verbose_name': 'Пункт шаблона чеклиста',
                'verbose_name_plural': 'Пункты шаблонов чеклистов',
                'ordering': ['template', 'section__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название Местоположения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Местоположение',
                'verbose_name_plural': 'Местоположения',
                'ordering': ['name'],
            },
        ),
    ]
