<<<<<<< HEAD
# Generated by Django 5.1 on 2025-06-15 23:30
=======
# Generated by Django 5.1 on 2025-05-11 20:53
>>>>>>> servicedesk

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('tasks', '0004_alter_task_status'),
>>>>>>> servicedesk
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название Точки/Комнаты')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Точка/Комната Чеклиста',
                'verbose_name_plural': 'Точки/Комнаты Чеклистов',
                'ordering': ['location__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True, verbose_name='Ответ (текст/выбор)')),
                ('numeric_value', models.FloatField(blank=True, null=True, verbose_name='Числовое значение ответа')),
                ('boolean_value', models.BooleanField(blank=True, null=True, verbose_name='Булево значение ответа')),
                ('date_value', models.DateField(blank=True, null=True, verbose_name='Значение типа Дата')),
                ('datetime_value', models.DateTimeField(blank=True, null=True, verbose_name='Значение типа Дата и время')),
                ('time_value', models.TimeField(blank=True, null=True, verbose_name='Значение типа Время')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='checklist_attachments/%Y/%m/%d/', verbose_name='Прикрепленный файл')),
                ('media_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на медиа (URL)')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарий к пункту')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('ok', 'OK'), ('not_ok', 'Не OK'), ('na', 'Неприменимо')], db_index=True, default='pending', max_length=20, verbose_name='Статус пункта')),
                ('is_corrected', models.BooleanField(default=False, help_text='Отметьте, если проблема, указанная в этом пункте, была устранена.', verbose_name='Проблема исправлена')),
                ('recorded_at', models.DateTimeField(auto_now=True, verbose_name='Время последней записи/обновления')),
            ],
            options={
                'verbose_name': 'Результат пункта чеклиста',
                'verbose_name_plural': 'Результаты пунктов чеклиста',
                'ordering': ['checklist_run', 'template_item__section__order', 'template_item__order', 'template_item_id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название секции')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Секция шаблона',
                'verbose_name_plural': 'Секции шаблона',
                'ordering': ['template', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Активные шаблоны доступны для создания новых чеклистов.', verbose_name='Активен')),
                ('version', models.CharField(blank=True, default='1.0', max_length=20, verbose_name='Версия')),
                ('is_archived', models.BooleanField(default=False, help_text='Архивированные шаблоны скрыты из основного списка и не могут быть использованы для новых чеклистов.', verbose_name='Архивирован')),
                ('frequency', models.CharField(blank=True, help_text='Например: ежедневно, еженедельно по понедельникам, раз в месяц 15 числа.', max_length=50, verbose_name='Периодичность')),
                ('next_due_date', models.DateField(blank=True, help_text='Для автоматического планирования (если реализовано).', null=True, verbose_name='След. дата выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Шаблон чеклиста',
                'verbose_name_plural': 'Шаблоны чеклистов',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.TextField(verbose_name='Текст пункта/вопроса')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в секции')),
                ('answer_type', models.CharField(choices=[('text', 'Текстовое поле'), ('number', 'Числовое поле'), ('scale_1_4', 'Оценка 1–4'), ('scale_1_5', 'Оценка 1–5'), ('yes_no', 'Да / Нет'), ('yes_no_meh', 'Да / Нет / Не очень'), ('boolean', 'Да/Нет (Boolean)'), ('date', 'Дата'), ('datetime', 'Дата и время'), ('time', 'Время'), ('file', 'Файл'), ('url', 'Ссылка')], default='text', max_length=20, verbose_name='Тип ответа')),
                ('help_text', models.CharField(blank=True, help_text='Дополнительная информация или инструкции для пункта.', max_length=255, verbose_name='Подсказка')),
                ('default_value', models.CharField(blank=True, help_text='Будет подставлено при создании чеклиста. Формат зависит от типа ответа.', max_length=255, verbose_name='Значение по умолчанию')),
            ],
            options={
                'verbose_name': 'Пункт шаблона чеклиста',
                'verbose_name_plural': 'Пункты шаблонов чеклистов',
                'ordering': ['template', 'section__order', 'section__title', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Тег шаблона чеклиста',
                'verbose_name_plural': 'Теги шаблонов чеклиста',
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField(db_index=True, verbose_name='object ID')),
            ],
            options={
                'verbose_name': 'Связь шаблона чеклиста и тега',
                'verbose_name_plural': 'Связи шаблонов чеклиста и тегов',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название Местоположения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='location_logos/%Y/%m/', verbose_name='Логотип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Местоположение',
                'verbose_name_plural': 'Местоположения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата/Время начала')),
                ('notes', models.TextField(blank=True, verbose_name='Общие примечания к чеклисту')),
                ('is_complete', models.BooleanField(db_index=True, default=False, help_text='Отмечается, когда все пункты заполнены и чеклист отправлен.', verbose_name='Завершен')),
                ('completion_time', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В процессе'), ('submitted', 'Отправлено'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Время одобрения/отклонения')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Процент выполнения или другая метрика.', max_digits=5, null=True, verbose_name='Оценка (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('external_reference', models.CharField(blank=True, help_text='ID из внешней системы, если применимо.', max_length=255, null=True, verbose_name='Внешняя ссылка/ID')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_checklists', to=settings.AUTH_USER_MODEL, verbose_name='Одобрено/Отклонено кем')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_checklists', to=settings.AUTH_USER_MODEL, verbose_name='Кем выполнен')),
            ],
            options={
                'verbose_name': 'Выполненный чеклист (Прогон)',
                'verbose_name_plural': 'Выполненные чеклисты (Прогоны)',
                'ordering': ['-performed_at', '-created_at'],
                'permissions': [('confirm_checklist', 'Может подтверждать чеклист')],
            },
        ),
    ]
