# Generated by Django 5.1 on 2025-05-30 22:04

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'ordering': ['-performed_at', '-created_at'], 'verbose_name': 'Выполненный чеклист (Прогон)', 'verbose_name_plural': 'Выполненные чеклисты (Прогоны)'},
        ),
        migrations.AlterModelOptions(
            name='checklistresult',
            options={'ordering': ['checklist_run', 'template_item__section__order', 'template_item__order', 'template_item_id'], 'verbose_name': 'Результат пункта чеклиста', 'verbose_name_plural': 'Результаты пунктов чеклиста'},
        ),
        migrations.AlterModelOptions(
            name='checklistsection',
            options={'ordering': ['template', 'order', 'title'], 'verbose_name': 'Секция шаблона', 'verbose_name_plural': 'Секции шаблона'},
        ),
        migrations.AlterModelOptions(
            name='checklisttemplateitem',
            options={'ordering': ['template', 'section__order', 'section__title', 'order', 'id'], 'verbose_name': 'Пункт шаблона чеклиста', 'verbose_name_plural': 'Пункты шаблонов чеклистов'},
        ),
        migrations.AlterField(
            model_name='checklist',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время одобрения/отклонения'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_checklists', to=settings.AUTH_USER_MODEL, verbose_name='Одобрено/Отклонено кем'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='external_reference',
            field=models.CharField(blank=True, help_text='ID из внешней системы, если применимо.', max_length=255, null=True, verbose_name='Внешняя ссылка/ID'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='is_complete',
            field=models.BooleanField(db_index=True, default=False, help_text='Отмечается, когда все пункты заполнены и чеклист отправлен.', verbose_name='Завершен'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_runs', to='checklists.location', verbose_name='Местоположение выполнения'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Общие примечания к чеклисту'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_checklists', to=settings.AUTH_USER_MODEL, verbose_name='Кем выполнен'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_runs', to='checklists.checklistpoint', verbose_name='Точка выполнения'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Процент выполнения или другая метрика.', max_digits=5, null=True, verbose_name='Оценка (%)'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В процессе'), ('submitted', 'Отправлено'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='checklistresult',
            name='boolean_value',
            field=models.BooleanField(blank=True, null=True, verbose_name='Булево значение ответа'),
        ),
        migrations.AlterField(
            model_name='checklistresult',
            name='checklist_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='checklists.checklist', verbose_name='Прогон чеклиста'),
        ),
        migrations.AlterField(
            model_name='checklistresult',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Комментарий к пункту'),
        ),
        migrations.AlterField(
            model_name='checklistresult',
            name='date_value',
            field=models.DateField(blank=True, null=True, verbose_name='Значение типа Дата'),
        ),
        migrations.AlterField(
            model_name='checklistresult',
            name='datetime_value',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Значение типа Дата и время'),
        ),
        migrations.AlterField(
            model_name='checklistresult',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='checklist_attachments/%Y/%m/%d/', verbose_name='Прикрепленный файл'),
        ),
        migrations.AlterField(
            model_name='checklistresult',
            name='is_corrected',
            field=models.BooleanField(default=False, help_text='Отметьте, если проблема, указанная в этом пункте, была устранена.', verbose_name='Проблема исправлена'),
        ),
        migrations.AlterField(
            model_name='checklistresult',
            name='media_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на медиа (URL)'),
        ),
        migrations.AlterField(
            model_name='checklistresult',
            name='numeric_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Числовое значение ответа'),
        ),
        migrations.AlterField(
            model_name='checklistresult',
            name='recorded_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последней записи/обновления'),
        ),
        migrations.AlterField(
            model_name='checklistresult',
            name='template_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='checklists.checklisttemplateitem', verbose_name='Пункт шаблона'),
        ),
        migrations.AlterField(
            model_name='checklistresult',
            name='time_value',
            field=models.TimeField(blank=True, null=True, verbose_name='Значение типа Время'),
        ),
        migrations.AlterField(
            model_name='checklistsection',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='checklistsection',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='checklists.checklisttemplate', verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='frequency',
            field=models.CharField(blank=True, help_text='Например: ежедневно, еженедельно по понедельникам, раз в месяц 15 числа.', max_length=50, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активные шаблоны доступны для создания новых чеклистов.', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Архивированные шаблоны скрыты из основного списка и не могут быть использованы для новых чеклистов.', verbose_name='Архивирован'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='next_due_date',
            field=models.DateField(blank=True, help_text='Для автоматического планирования (если реализовано).', null=True, verbose_name='След. дата выполнения'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Разделяйте теги запятыми.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='checklisttemplateitem',
            name='default_value',
            field=models.CharField(blank=True, help_text='Будет подставлено при создании чеклиста. Формат зависит от типа ответа.', max_length=255, verbose_name='Значение по умолчанию'),
        ),
        migrations.AlterField(
            model_name='checklisttemplateitem',
            name='help_text',
            field=models.CharField(blank=True, help_text='Дополнительная информация или инструкции для пункта.', max_length=255, verbose_name='Подсказка'),
        ),
        migrations.AlterField(
            model_name='checklisttemplateitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в секции'),
        ),
        migrations.AlterField(
            model_name='checklisttemplateitem',
            name='parent_item',
            field=models.ForeignKey(blank=True, help_text='Для создания вложенных (зависимых) пунктов.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_items', to='checklists.checklisttemplateitem', verbose_name='Родительский пункт'),
        ),
        migrations.AlterField(
            model_name='checklisttemplateitem',
            name='target_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_items', to='checklists.checklistpoint', verbose_name='Конкретная Точка (если отличается от общей)'),
        ),
    ]
