# Generated by Django 5.1 on 2025-06-15 23:04

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('tasks', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_checklists', to=settings.AUTH_USER_MODEL, verbose_name='Одобрено/Отклонено кем'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_checklists', to=settings.AUTH_USER_MODEL, verbose_name='Кем выполнен'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='tasks.task', verbose_name='Связанная задача'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_runs', to='checklists.checklistpoint', verbose_name='Точка выполнения'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='checklist_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='checklists.checklist', verbose_name='Прогон чеклиста'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checklist_results', to=settings.AUTH_USER_MODEL, verbose_name='Создано кем'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_checklist_results', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено кем'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates', to='tasks.taskcategory', verbose_name='Категория (из Задач)'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='target_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates', to='checklists.checklistpoint', verbose_name='Целевая Точка/Комната'),
        ),
        migrations.AddField(
            model_name='checklistsection',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='checklists.checklisttemplate', verbose_name='Шаблон'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='checklists.checklisttemplate', verbose_name='Шаблон'),
        ),
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='parent_item',
            field=models.ForeignKey(blank=True, help_text='Для создания вложенных (зависимых) пунктов.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_items', to='checklists.checklisttemplateitem', verbose_name='Родительский пункт'),
        ),
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='checklists.checklistsection', verbose_name='Секция'),
        ),
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='target_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_items', to='checklists.checklistpoint', verbose_name='Конкретная Точка (если отличается от общей)'),
        ),
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklisttemplate', verbose_name='Шаблон'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='template_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='checklists.checklisttemplateitem', verbose_name='Пункт шаблона'),
        ),
        migrations.AddField(
            model_name='checklisttemplatetaggeditem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type'),
        ),
        migrations.AddField(
            model_name='checklisttemplatetaggeditem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='checklists.checklisttemplatetag'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Разделяйте теги запятыми.', through='checklists.ChecklistTemplateTaggedItem', to='checklists.ChecklistTemplateTag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_locations', to='checklists.location', verbose_name='Родительское Местоположение'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='target_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates', to='checklists.location', verbose_name='Целевое Местоположение'),
        ),
        migrations.AddField(
            model_name='checklistpoint',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='checklists.location', verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_runs', to='checklists.location', verbose_name='Местоположение выполнения'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistsection',
            unique_together={('template', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='checklisttemplateitem',
            unique_together={('template', 'section', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='checklistresult',
            unique_together={('checklist_run', 'template_item')},
        ),
        migrations.AddConstraint(
            model_name='checklistpoint',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='unique_point_per_location'),
        ),
    ]
