# Generated by Django 5.1 on 2025-04-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklisttemplateitem',
            name='item_text',
            field=models.TextField(verbose_name='Текст пункта/вопроса'),
        ),
    ]
