# Generated by Django 5.1 on 2025-04-30 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_alter_checklisttemplateitem_item_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название Точки/Комнаты')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Точка/Комната Чеклиста',
                'verbose_name_plural': 'Точки/Комнаты Чеклистов',
                'ordering': ['location__name', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='checklist',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Общие примечания к Прогону'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_runs', to='checklists.checklistpoint', verbose_name='Точка/Комната Прогона'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='target_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates', to='checklists.checklistpoint', verbose_name='Целевая Точка/Комната'),
        ),
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='target_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_items', to='checklists.checklistpoint', verbose_name='Целевая Точка/Комната для Пункта'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название Местоположения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_locations', to='checklists.location', verbose_name='Родительское Местоположение')),
            ],
            options={
                'verbose_name': 'Местоположение',
                'verbose_name_plural': 'Местоположения',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='checklistpoint',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='checklists.location', verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='target_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates', to='checklists.location', verbose_name='Целевое Местоположение'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_runs', to='checklists.location', verbose_name='Местоположение Прогона'),
        ),
        migrations.AddConstraint(
            model_name='checklistpoint',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='unique_point_per_location'),
        ),
    ]
