# Generated by Django 5.1 on 2025-06-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_alter_checklist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='location_logos/', verbose_name='Логотип'),
        ),
    ]
