# Generated by Django 5.1 on 2025-06-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_location_logo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='location_logos/%Y/%m/', verbose_name='Логотип'),
        ),
    ]
