# Generated by Django 5.1 on 2025-05-01 11:03

import django.db.models.deletion
import django.utils.timezone
import taggit.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_checklistpoint_alter_checklist_notes_checklist_point_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название секции')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Секция шаблона',
                'verbose_name_plural': 'Секции шаблона',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='checklist',
            options={'ordering': ['-performed_at', '-created_at'], 'verbose_name': 'Выполненный чеклист', 'verbose_name_plural': 'Выполненные чеклисты'},
        ),
        migrations.AlterModelOptions(
            name='checklistresult',
            options={'ordering': ['checklist_run', 'template_item__section__order', 'template_item__order'], 'verbose_name': 'Результат пункта', 'verbose_name_plural': 'Результаты пунктов'},
        ),
        migrations.AlterModelOptions(
            name='checklisttemplateitem',
            options={'ordering': ['template', 'section__order', 'order', 'id'], 'verbose_name': 'Пункт шаблона чеклиста', 'verbose_name_plural': 'Пункты шаблонов чеклистов'},
        ),
        migrations.RemoveConstraint(
            model_name='checklistresult',
            name='unique_result_per_item_run',
        ),
        migrations.RemoveIndex(
            model_name='checklist',
            name='checklists__perform_e6c7a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='checklist',
            name='checklists__templat_3eb993_idx',
        ),
        migrations.RemoveIndex(
            model_name='checklist',
            name='checklists__perform_f00ef6_idx',
        ),
        migrations.RemoveIndex(
            model_name='checklist',
            name='checklists__is_comp_365067_idx',
        ),
        migrations.RemoveIndex(
            model_name='checklistresult',
            name='checklists__checkli_ded83f_idx',
        ),
        migrations.RemoveIndex(
            model_name='checklistresult',
            name='checklists__status_d0144d_idx',
        ),
        migrations.AddField(
            model_name='checklist',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время одобрения'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_checklists', to=settings.AUTH_USER_MODEL, verbose_name='Одобрено кем'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklist',
            name='external_reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Внешняя ссылка'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В процессе'), ('submitted', 'Отправлено'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='in_progress', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='boolean_value',
            field=models.BooleanField(blank=True, null=True, verbose_name='Булево значение'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checklist_results', to=settings.AUTH_USER_MODEL, verbose_name='Создано кем'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='date_value',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='datetime_value',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='checklist_files/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='is_corrected',
            field=models.BooleanField(default=False, verbose_name='Исправлено'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='media_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на медиа'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='numeric_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Числовое значение'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='time_value',
            field=models.TimeField(blank=True, null=True, verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_checklist_results', to=settings.AUTH_USER_MODEL, verbose_name='Обновлено кем'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='value',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ (текст/выбор)'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='frequency',
            field=models.CharField(blank=True, max_length=50, verbose_name='Периодичность'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Архивирован'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='next_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='След. дата выполнения'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='version',
            field=models.CharField(blank=True, default='1.0', max_length=20, verbose_name='Версия'),
        ),
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='answer_type',
            field=models.CharField(choices=[('text', 'Текстовое поле'), ('number', 'Числовое поле'), ('scale_1_4', 'Оценка 1–4'), ('scale_1_5', 'Оценка 1–5'), ('yes_no', 'Да / Нет'), ('yes_no_meh', 'Да / Нет / Не очень'), ('boolean', 'Да/Нет (Boolean)'), ('date', 'Дата'), ('datetime', 'Дата и время'), ('time', 'Время'), ('file', 'Файл'), ('url', 'Ссылка')], default='text', max_length=20, verbose_name='Тип ответа'),
        ),
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='default_value',
            field=models.CharField(blank=True, max_length=255, verbose_name='Значение по умолчанию'),
        ),
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='help_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подсказка'),
        ),
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='parent_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_items', to='checklists.checklisttemplateitem', verbose_name='Родительский пункт'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_runs', to='checklists.location', verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='performed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата/Время начала'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_runs', to='checklists.checklistpoint', verbose_name='Точка'),
        ),
        migrations.AlterField(
            model_name='checklistpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='checklistpoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='checklistresult',
            name='checklist_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='checklists.checklist', verbose_name='Прогон'),
        ),
        migrations.AlterField(
            model_name='checklistresult',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='checklistresult',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='checklistresult',
            name='recorded_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Записано'),
        ),
        migrations.AlterField(
            model_name='checklistresult',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает ответа'), ('ok', 'OK'), ('not_ok', 'Не OK'), ('na', 'Неприменимо')], db_index=True, default='pending', max_length=20, verbose_name='Статус пункта'),
        ),
        migrations.AlterField(
            model_name='checklistresult',
            name='template_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='checklists.checklisttemplateitem', verbose_name='Пункт'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='checklisttemplateitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='checklisttemplateitem',
            name='target_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_items', to='checklists.checklistpoint', verbose_name='Целевая Точка'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistresult',
            unique_together={('checklist_run', 'template_item')},
        ),
        migrations.AddField(
            model_name='checklistsection',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='checklists.checklisttemplate'),
        ),
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='checklists.checklistsection', verbose_name='Секция'),
        ),
        migrations.AlterUniqueTogether(
            name='checklisttemplateitem',
            unique_together={('template', 'section', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='checklistsection',
            unique_together={('template', 'order')},
        ),
    ]
