# Generated by Django 5.1 on 2024-08-12 15:56

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'branch',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricalSensor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=255)),
                ('sensor_type', models.CharField(max_length=255)),
                ('sensor_name', models.CharField(max_length=255)),
                ('last_reading', models.FloatField()),
                ('last_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical sensor',
                'verbose_name_plural': 'historical sensors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterModelOptions(
            name='netpingdevice',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='netpingdevice',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='netpingdevice',
            name='hostname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='netpingdevice',
            name='snmp_community_ro',
            field=models.CharField(blank=True, default='snmp2netread', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='netpingdevice',
            name='snmp_community_rw',
            field=models.CharField(blank=True, default='netman', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='netpingdevice',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='netpingdevice',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='netpingdevice',
            unique_together={('hostname', 'ip_address')},
        ),
        migrations.AddIndex(
            model_name='netpingdevice',
            index=models.Index(fields=['status', 'hostname', 'ip_address'], name='switches_status_1a6758_idx'),
        ),
        migrations.AlterModelTable(
            name='netpingdevice',
            table='switches',
        ),
        migrations.AddField(
            model_name='historicalsensor',
            name='device',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='netping.netpingdevice'),
        ),
        migrations.AddField(
            model_name='historicalsensor',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
