# Generated by Django 5.1 on 2024-08-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsensor',
            name='sensor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
