# Generated by Django 5.1 on 2024-08-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netping', '0002_branch_historicalsensor_alter_netpingdevice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='netpingdevice',
            name='uptime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
