# Generated by Django 5.1 on 2024-08-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netping', '0002_alter_historicalsensor_sensor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsensor',
            name='value_current_long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='value_current_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
