# Generated by Django 5.1 on 2024-08-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netping', '0003_netpingdevice_uptime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netpingdevice',
            name='snmp_community_ro',
            field=models.CharField(blank=True, default='SWITCH', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='netpingdevice',
            name='snmp_community_rw',
            field=models.CharField(blank=True, default='SWITCH', max_length=20, null=True),
        ),
    ]
