# Generated by Django 5.1 on 2024-08-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netping', '0004_alter_netpingdevice_snmp_community_ro_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='netpingdevice',
            new_name='netping_status_a73493_idx',
            old_name='switches_status_1a6758_idx',
        ),
        migrations.AlterField(
            model_name='netpingdevice',
            name='snmp_community_ro',
            field=models.CharField(blank=True, default='device', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='netpingdevice',
            name='snmp_community_rw',
            field=models.CharField(blank=True, default='device', max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='netpingdevice',
            table='netping',
        ),
    ]
