# Generated by Django 5.1 on 2024-08-13 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netping', '0005_rename_switches_status_1a6758_idx_netping_status_a73493_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=100)),
                ('problem_severity', models.CharField(choices=[('notclassified', 'Not classified'), ('information', 'Information'), ('warning', 'Warning'), ('average', 'Average'), ('high', 'High'), ('disaster', 'Disaster')], default='notclassified', max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netping.netpingdevice')),
            ],
        ),
    ]
