# Generated by Django 5.1 on 2024-08-13 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netping', '0007_rename_device_problems_host_alter_sensor_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsensor',
            name='problem',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='netping.problems'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='problem',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='netping.problems'),
        ),
    ]
