# Generated by Django 5.1 on 2024-08-13 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netping', '0008_historicalsensor_problem_sensor_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='problem',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='netping.problems'),
        ),
    ]
