# Generated by Django 5.1 on 2024-08-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netping', '0009_alter_sensor_problem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problems',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='historicalproblems',
            name='comments',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalproblems',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalproblems',
            name='last_updated',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalproblems',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='problems',
            name='comments',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='problems',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='problems',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='problems',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddIndex(
            model_name='problems',
            index=models.Index(fields=['status', 'host'], name='problems_status_80a81f_idx'),
        ),
        migrations.AlterModelTable(
            name='problems',
            table='problems',
        ),
    ]
