# Generated by Django 5.1 on 2024-08-13 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netping', '0010_alter_problems_options_historicalproblems_comments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('last_update', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comments',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='historicalproblems',
            name='comments',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='netping.comments'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netping.comments'),
        ),
    ]
