# Generated by Django 5.1 on 2024-08-13 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netping', '0011_comments_alter_historicalproblems_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsensor',
            name='problem',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='netping.problems'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='netping.problems'),
        ),
    ]
