# Generated by Django 5.1 on 2024-08-14 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netping', '0012_alter_historicalsensor_problem_alter_sensor_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='netping.comments'),
        ),
    ]
