# Generated by Django 5.1 on 2024-08-14 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netping', '0013_alter_problems_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='problem',
            field=models.ForeignKey(null=True, blank=True, on_delete=models.CASCADE, related_name='sensor', to='netping.Problems'),
        ),
    ]

