# Generated by Django 5.1 on 2024-08-14 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netping', '0014_alter_sensor_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor', to='netping.problems'),
        ),
    ]
