# Generated by Django 5.1 on 2024-08-14 07:15

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netping', '0015_alter_sensor_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsensor',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='netpingdevice',
            name='snmp_community_ro',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='SWITCH', null=True),
        ),
        migrations.AlterField(
            model_name='netpingdevice',
            name='snmp_community_rw',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='SWITCH', null=True),
        ),
    ]
