# Generated by Django 5.1 on 2024-08-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netping', '0016_historicalsensor_status_sensor_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsensor',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
