# Generated by Django 5.1 on 2024-08-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netping', '0017_alter_historicalsensor_status_alter_sensor_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsensor',
            old_name='last_reading',
            new_name='value_current',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='last_reading',
            new_name='value_current',
        ),
        migrations.AddField(
            model_name='historicalsensor',
            name='value_high_trshld',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalsensor',
            name='value_low_trshld',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='value_high_trshld',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensor',
            name='value_low_trshld',
            field=models.IntegerField(default=0),
        ),
    ]
