# Generated by Django 5.1 on 2024-08-14 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netping', '0018_rename_last_reading_historicalsensor_value_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_set', to='netping.netpingdevice'),
        ),
    ]
