# Generated by Django 5.1 on 2024-08-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netping', '0019_alter_sensor_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsensor',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='problem',
        ),
    ]
