# Generated by Django 5.1 on 2024-08-14 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netping', '0020_remove_historicalsensor_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproblems',
            name='sensor',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='netping.sensor'),
        ),
        migrations.AddField(
            model_name='problems',
            name='sensor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='problem_set', to='netping.sensor'),
        ),
    ]
