# Generated by Django 5.1 on 2024-08-14 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netping', '0021_historicalproblems_sensor_problems_sensor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproblems',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='problems',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='problem',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='netping.problems'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_set', to='netping.netpingdevice'),
        ),
    ]
