# Generated by Django 5.1 on 2024-08-14 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netping', '0022_remove_historicalproblems_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='problem',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='netping.problems'),
        ),
    ]
