# Generated by Django 5.0.6 on 2025-02-25 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Введите название кампании. Например: 'Рекламная кампания Q4', 'Релиз продукта 2.0', 'Обучение персонала'", max_length=200, verbose_name='Название кампании')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание кампании (необязательно).', verbose_name='Описание кампании')),
                ('start_date', models.DateField(blank=True, help_text='Укажите дату начала кампании (необязательно).', null=True, verbose_name='Дата начала кампании')),
                ('end_date', models.DateField(blank=True, help_text='Укажите дату завершения кампании (необязательно).', null=True, verbose_name='Дата завершения кампании')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Кампания',
                'verbose_name_plural': 'Кампании',
                'ordering': ['name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Введите название категории задач, например: 'Маркетинг', 'Разработка', 'HR'", max_length=100, unique=True, verbose_name='Название категории задач')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание категории задач (необязательно).', verbose_name='Описание категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Категория задач',
                'verbose_name_plural': 'Категории задач',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название статуса задачи. Должно быть уникальным.', max_length=50, unique=True, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус задачи',
                'verbose_name_plural': 'Статусы задач',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(blank=True, help_text='Автоматически генерируемый номер задачи.', max_length=20, unique=True, verbose_name='Номер задачи')),
                ('task_type', models.CharField(help_text="Опишите тип задачи, например: 'Разработка главной страницы', 'Подготовка презентации', 'Проведение переговоров'", max_length=200, verbose_name='Тип задачи')),
                ('description', models.TextField(help_text='Подробное описание задачи, которую необходимо выполнить.', verbose_name='Описание задачи')),
                ('priority', models.IntegerField(choices=[(1, 'Высокий'), (2, 'Выше среднего'), (3, 'Средний'), (4, 'Ниже среднего'), (5, 'Низкий')], default=3, help_text='Укажите приоритет задачи.', verbose_name='Приоритет')),
                ('deadline', models.DateTimeField(blank=True, help_text='Укажите срок выполнения задачи (необязательно).', null=True, verbose_name='Срок выполнения')),
                ('start_date', models.DateTimeField(blank=True, help_text='Укажите дату начала выполнения задачи (необязательно).', null=True, verbose_name='Дата начала')),
                ('completion_date', models.DateTimeField(blank=True, help_text="Укажите дату фактического завершения задачи (заполняется автоматически при смене статуса на 'Выполнена').", null=True, verbose_name='Дата завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('estimated_time', models.DurationField(blank=True, help_text="Укажите оценочное время выполнения задачи (например, '1 час 30 минут').", null=True, verbose_name='Оценочное время')),
                ('notes', models.TextField(blank=True, help_text='Добавьте любые заметки или комментарии к задаче (необязательно).', verbose_name='Заметки/Комментарии')),
                ('assignee', models.ForeignKey(blank=True, help_text='Выберите ответственного сотрудника за выполнение задачи (необязательно).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('campaign', models.ForeignKey(help_text='Выберите кампанию, к которой относится задача.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm_core.campaign', verbose_name='Кампания')),
                ('created_by', models.ForeignKey(blank=True, help_text='Пользователь, создавший задачу (заполняется автоматически).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='Автор задачи')),
                ('category', models.ForeignKey(blank=True, help_text='Выберите категорию задачи (необязательно).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm_core.taskcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['priority', 'deadline', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='task_photos/', verbose_name='Фотография')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('description', models.CharField(blank=True, help_text='Добавьте описание к фотографии (необязательно).', max_length=255, verbose_name='Описание фотографии')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_photos', to='crm_core.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Фотография/Вложение к задаче',
                'verbose_name_plural': 'Фотографии/Вложения к задачам',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='photos',
            field=models.ManyToManyField(blank=True, help_text='Добавьте фотографии или другие вложения к задаче (необязательно).', related_name='tasks', to='crm_core.taskphoto', verbose_name='Фотографии/Вложения'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=1, help_text='Выберите текущий статус задачи.', on_delete=django.db.models.deletion.PROTECT, to='crm_core.taskstatus', verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='TaskSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Введите название подкатегории задач, например: 'Контент', 'Frontend', 'Подбор персонала'", max_length=100, verbose_name='Название подкатегории задач')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание подкатегории задач (необязательно).', verbose_name='Описание подкатегории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(help_text='Выберите категорию, к которой относится подкатегория.', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='crm_core.taskcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория задач',
                'verbose_name_plural': 'Подкатегории задач',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Выберите подкатегорию задачи (необязательно).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm_core.tasksubcategory', verbose_name='Подкатегория'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Введите название команды, например: 'Маркетинг', 'Разработка', 'Продажи'", max_length=100, verbose_name='Название команды')),
                ('description', models.TextField(blank=True, help_text='Дополнительное описание команды (необязательно).', verbose_name='Описание команды')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('members', models.ManyToManyField(blank=True, help_text='Выберите участников команды (необязательно).', related_name='teams_member', to=settings.AUTH_USER_MODEL, verbose_name='Участники команды')),
                ('team_leader', models.ForeignKey(blank=True, help_text='Выберите руководителя команды (необязательно).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_managed', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель команды')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Выберите команду, назначенную на выполнение задачи (необязательно).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm_core.team', verbose_name='Команда'),
        ),
    ]
