# Generated by Django 5.0.6 on 2025-02-25 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0002_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='task_categories',
            field=models.ManyToManyField(blank=True, help_text='Выберите категории задач, за которые отвечает команда (необязательно).', related_name='teams', to='crm_core.taskcategory', verbose_name='Категории задач'),
        ),
        migrations.CreateModel(
            name='TaskUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('executor', 'Исполнитель'), ('watcher', 'Наблюдатель'), ('responsible', 'Ответственный')], default='executor', help_text='Выберите роль пользователя в данной задаче.', max_length=20, verbose_name='Роль пользователя в задаче')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='crm_core.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_roles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Роль пользователя в задаче',
                'verbose_name_plural': 'Роли пользователей в задачах',
                'unique_together': {('task', 'user', 'role')},
            },
        ),
    ]
