# Generated by Django 5.0.6 on 2025-02-25 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0003_team_task_categories_taskuserrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcategory',
            name='last_assigned_team',
            field=models.ForeignKey(blank=True, help_text='Команда, которой последней была назначена задача этой категории (автоматически).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_category_tasks', to='crm_core.team', verbose_name='Последняя назначенная команда'),
        ),
    ]
