# Generated by Django 5.0.6 on 2025-02-25 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0004_taskcategory_last_assigned_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.AlterField(
            model_name='task',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Выберите проект, к которому относится задача.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm_core.campaign', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('on_hold', 'Отложена'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='new', help_text='Выберите текущий статус задачи.', max_length=20, verbose_name='Статус'),
        ),
    ]
