# Generated by Django 5.0.6 on 2025-02-25 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0005_remove_task_task_type_alter_task_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(default=0, help_text="Опишите тип задачи, например: 'Разработка главной страницы', 'Подготовка презентации', 'Проведение переговоров'", max_length=200, verbose_name='Тип задачи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='campaign',
            field=models.ForeignKey(default=0, help_text='Выберите кампанию, к которой относится задача.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm_core.campaign', verbose_name='Кампания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=1, help_text='Выберите текущий статус задачи.', on_delete=django.db.models.deletion.PROTECT, to='crm_core.taskstatus', verbose_name='Статус'),
        ),
    ]
