# Generated by Django 5.0.6 on 2025-02-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0006_task_task_type_alter_task_campaign_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('on_hold', 'Отложена'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='new', help_text='Выберите текущий статус задачи.', max_length=20, verbose_name='Статус'),
        ),
    ]
