# Generated by Django 5.0.6 on 2025-03-08 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0007_alter_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(db_index=True, help_text="Введите название кампании. Например: 'Рекламная кампания Q4', 'Релиз продукта 2.0', 'Обучение персонала'", max_length=200, verbose_name='Название кампании'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(db_index=True, help_text="Введите название роли пользователя, например: 'Администратор', 'Менеджер', 'Бригадир'", max_length=50, unique=True, verbose_name='Название роли'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Укажите срок выполнения задачи (необязательно).', null=True, verbose_name='Срок выполнения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Высокий'), (2, 'Выше среднего'), (3, 'Средний'), (4, 'Ниже среднего'), (5, 'Низкий')], db_index=True, default=3, help_text='Укажите приоритет задачи.', verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('on_hold', 'Отложена'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], db_index=True, default='new', help_text='Выберите текущий статус задачи.', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_number',
            field=models.CharField(blank=True, db_index=True, help_text='Автоматически генерируемый номер задачи.', max_length=20, unique=True, verbose_name='Номер задачи'),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='name',
            field=models.CharField(db_index=True, help_text="Введите название категории задач, например: 'Маркетинг', 'Разработка', 'HR'", max_length=100, unique=True, verbose_name='Название категории задач'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='name',
            field=models.CharField(db_index=True, help_text='Введите название статуса задачи. Должно быть уникальным.', max_length=50, unique=True, verbose_name='Название статуса'),
        ),
        migrations.AlterField(
            model_name='tasksubcategory',
            name='name',
            field=models.CharField(db_index=True, help_text="Введите название подкатегории задач, например: 'Контент', 'Frontend', 'Подбор персонала'", max_length=100, verbose_name='Название подкатегории задач'),
        ),
        migrations.AlterField(
            model_name='taskuserrole',
            name='role',
            field=models.CharField(choices=[('executor', 'Исполнитель'), ('watcher', 'Наблюдатель'), ('responsible', 'Ответственный')], db_index=True, default='executor', help_text='Выберите роль пользователя в данной задаче.', max_length=20, verbose_name='Роль пользователя в задаче'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(db_index=True, help_text="Введите название команды, например: 'Маркетинг', 'Разработка', 'Продажи'", max_length=100, verbose_name='Название команды'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['name'], name='campaign_name_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name'], name='role_name_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority', 'deadline', '-created_at'], name='task_default_ordering_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_number'], name='task_task_number_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='task_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='task_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deadline'], name='task_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcategory',
            index=models.Index(fields=['name'], name='taskcategory_name_idx'),
        ),
        migrations.AddIndex(
            model_name='taskphoto',
            index=models.Index(fields=['task'], name='taskphoto_task_idx'),
        ),
        migrations.AddIndex(
            model_name='taskstatus',
            index=models.Index(fields=['name'], name='taskstatus_name_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksubcategory',
            index=models.Index(fields=['category', 'name'], name='subcat_catname_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksubcategory',
            index=models.Index(fields=['name'], name='tasksubcategory_name_idx'),
        ),
        migrations.AddIndex(
            model_name='taskuserrole',
            index=models.Index(fields=['task', 'user', 'role'], name='taskuserrole_unique_role_idx'),
        ),
        migrations.AddIndex(
            model_name='taskuserrole',
            index=models.Index(fields=['task'], name='taskuserrole_task_idx'),
        ),
        migrations.AddIndex(
            model_name='taskuserrole',
            index=models.Index(fields=['user'], name='taskuserrole_user_idx'),
        ),
        migrations.AddIndex(
            model_name='taskuserrole',
            index=models.Index(fields=['role'], name='taskuserrole_role_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name'], name='team_name_idx'),
        ),
    ]
