# Generated by Django 5.0.6 on 2025-03-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0008_alter_campaign_name_alter_role_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
    ]
