# Generated by Django 5.0.6 on 2025-03-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0010_remove_task_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskStatus',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('on_hold', 'Отложена'), ('completed', 'Выполнена'), ('cancelled', 'Отменена'), ('overdue', 'Просрочена')], db_index=True, default='new', help_text='Выберите текущий статус задачи.', max_length=20, verbose_name='Статус'),
        ),
    ]
