# Generated by Django 5.0.6 on 2025-03-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0011_delete_taskstatus_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, blank=True, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskphoto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
