# Generated by Django 5.0.6 on 2025-03-08 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0012_taskphoto_created_at_taskphoto_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskphoto',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Фотография к задаче', 'verbose_name_plural': 'Фотографии к задачам'},
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_default_ordering_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_deadline_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskuserrole',
            name='taskuserrole_task_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskuserrole',
            name='taskuserrole_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='taskuserrole',
            name='taskuserrole_role_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='photos',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание кампании'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название кампании'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название роли'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm_core.campaign'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm_core.taskcategory'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Высокий'), (2, 'Выше среднего'), (3, 'Средний'), (4, 'Ниже среднего'), (5, 'Низкий')], db_index=True, default=3),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('on_hold', 'Отложена'), ('completed', 'Выполнена'), ('cancelled', 'Отменена'), ('overdue', 'Просрочена')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm_core.tasksubcategory'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True, verbose_name='Номер задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm_core.team'),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='last_assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_category_tasks', to='crm_core.team'),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='taskphoto',
            name='photo',
            field=models.ImageField(upload_to='task_photos/'),
        ),
        migrations.AlterField(
            model_name='taskphoto',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_photos', to='crm_core.task'),
        ),
        migrations.AlterField(
            model_name='taskphoto',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tasksubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='crm_core.taskcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tasksubcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание подкатегории'),
        ),
        migrations.AlterField(
            model_name='tasksubcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название подкатегории'),
        ),
        migrations.AlterField(
            model_name='taskuserrole',
            name='role',
            field=models.CharField(choices=[('executor', 'Исполнитель'), ('watcher', 'Наблюдатель'), ('responsible', 'Ответственный')], db_index=True, default='executor', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskuserrole',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='crm_core.task'),
        ),
        migrations.AlterField(
            model_name='taskuserrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание команды'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='teams_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название команды'),
        ),
        migrations.AlterField(
            model_name='team',
            name='task_categories',
            field=models.ManyToManyField(blank=True, related_name='teams', to='crm_core.taskcategory'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_managed', to=settings.AUTH_USER_MODEL),
        ),
    ]
