# Generated by Django 5.1 on 2025-03-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0013_alter_taskphoto_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AlterUniqueTogether(
            name='taskuserrole',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='taskuserrole',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskuserrole',
            name='user',
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.RemoveField(
            model_name='team',
            name='task_categories',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_leader',
        ),
    ]
