# Generated by Django 5.1 on 2025-03-16 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0014_delete_role_alter_taskuserrole_unique_together_and_more'),
        ('user_profiles', '0010_userprofile_image_role_team_taskuserrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategory',
            name='last_assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_category_tasks', to='user_profiles.team'),
        ),
        migrations.AlterField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='user_profiles.team'),
        ),
        migrations.AddField(
            model_name='task',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='crm_core.taskphoto'),
        ),
        migrations.DeleteModel(
            name='TaskUserRole',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
