# Generated by Django 5.1 on 2025-03-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0015_alter_taskcategory_last_assigned_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskphoto',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание фотографии'),
        ),
    ]
