# Generated by Django 5.1 on 2025-03-18 02:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0016_alter_taskphoto_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_number',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Номер задачи'),
        ),
    ]
