# Generated by Django 5.1 on 2025-03-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0017_alter_task_task_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True, verbose_name='Номер задачи'),
        ),
    ]
