# Generated by Django 5.1 on 2025-06-01 15:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0002_alter_checklist_options_and_more'),
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code Image')),
                ('short_description', models.CharField(blank=True, help_text="E.g., 'Feedback for Main Entrance' or 'Restroom A1'", max_length=100, verbose_name='Short Description for QR page')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_feedback_link', to='checklists.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'QR Code Link',
                'verbose_name_plural': 'QR Code Links',
                'ordering': ['location__name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Very Bad'), (2, '2 - Bad'), (3, '3 - Neutral'), (4, '4 - Good'), (5, '5 - Excellent')], verbose_name='Rating')),
                ('text', models.TextField(blank=True, verbose_name='Review Text')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='review_photos/', verbose_name='Photo')),
                ('contact_info', models.CharField(blank=True, help_text='Optional, if you want us to contact you.', max_length=255, verbose_name='Contact Information (Phone/Email)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('qr_code_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='qrfikr.qrcodelink', verbose_name='QR Code Link')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_reviews', to='tasks.task', verbose_name='Related Task')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
