# Generated by Django 5.1 on 2025-06-15 23:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('qr_image', models.ImageField(blank=True, upload_to='qr_codes/', verbose_name='QR Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='checklists.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'QR Link',
                'verbose_name_plural': 'QR Links',
                'ordering': ['location__name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('text', models.TextField(blank=True)),
                ('contact_info', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='review_photos/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('qr_code_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='qrfikr.qrcodelink')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
