# Generated by Django 5.1 on 2025-06-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrfikr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodelink',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/%Y/%m/%d/', verbose_name='QR Code Image'),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='review_photos/%Y/%m/%d/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Very Bad'), (2, '2 - Bad'), (3, '3 - Neutral'), (4, '4 - Good'), (5, '5 - Excellent')], db_index=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='review',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Submitted At'),
        ),
    ]
