# Generated by Django 5.1 on 2025-06-16 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0003_location_level"),
        ("qrfikr", "0001_initial"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcodelink",
            name="point",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qr_code",
                to="checklists.checklistpoint",
                verbose_name="Point",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tasks.taskcategory",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="qrcodelink",
            name="location",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qr_codes",
                to="checklists.location",
                verbose_name="Location",
            ),
        ),
    ]
