# Generated by Django 5.1 on 2025-06-17 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrfikr', '0002_add_point_category'),
        ('qrfikr', '0002_qrcodelink_point_review_category_and_more'),
    ]

    operations = [
    ]
