# Generated by Django 5.1 on 2025-06-17 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_location_level'),
        ('qrfikr', '0003_merge_20250617_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodelink',
            name='task_category',
        ),
        migrations.AlterField(
            model_name='qrcodelink',
            name='point',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='checklists.checklistpoint', verbose_name='Point'),
        ),
    ]
