# Generated by Django 5.1 on 2025-06-16 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_location_level'),
        ('qrfikr', '0003_merge_20250616_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcodelink',
            options={'ordering': ['location__name', 'point__name'], 'verbose_name': 'QR Link', 'verbose_name_plural': 'QR Links'},
        ),
        migrations.AlterField(
            model_name='qrcodelink',
            name='point',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='checklists.checklistpoint', verbose_name='Point'),
        ),
    ]
