# Generated by Django 5.1 on 2025-06-22 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0003_location_level"),
        ("qrfikr", "0004_remove_qrcodelink_task_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcodelink",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qr_codes",
                to="checklists.location",
                verbose_name="Location",
            ),
        ),
    ]
